log:
    stdout: true
    level: info

persistence:
    numHistoryShards: 4
    defaultStore: default
    visibilityStore: visibility
    datastores:
        default:
            sql:
                pluginName: "postgres12"
                databaseName: "temporal"
                connectAddr: "temporal-postgres:5432"
                connectProtocol: "tcp"
                user: "temporal"
                password: "temporal_password"
                maxConns: 20
                maxIdleConns: 20
                maxConnLifetime: 1h
                tls:
                    enabled: false
        visibility:
            sql:
                pluginName: "postgres12"
                databaseName: "temporal_visibility"
                connectAddr: "temporal-postgres:5432"
                connectProtocol: "tcp"
                user: "temporal"
                password: "temporal_password"
                maxConns: 10
                maxIdleConns: 10
                maxConnLifetime: 1h
                tls:
                    enabled: false

global:
    membership:
        maxJoinDuration: 30s
        broadcastAddress: ""
    metrics:
        prometheus:
            timerType: "histogram"
            listenAddress: "0.0.0.0:9090"

services:
    frontend:
        rpc:
            grpcPort: 7233
            membershipPort: 6933
            bindOnLocalHost: false
            bindOnIP: "0.0.0.0"

    matching:
        rpc:
            grpcPort: 7235
            membershipPort: 6935
            bindOnLocalHost: false
            bindOnIP: "0.0.0.0"

    history:
        rpc:
            grpcPort: 7234
            membershipPort: 6934
            bindOnLocalHost: false
            bindOnIP: "0.0.0.0"

    worker:
        rpc:
            grpcPort: 7239
            membershipPort: 6939
            bindOnLocalHost: false
            bindOnIP: "0.0.0.0"

clusterMetadata:
    enableGlobalNamespace: false
    failoverVersionIncrement: 10
    masterClusterName: "active"
    currentClusterName: "active"
    clusterInformation:
        active:
            enabled: true
            initialFailoverVersion: 1
            rpcName: "frontend"
            rpcAddress: "0.0.0.0:7233"

dcRedirectionPolicy:
    policy: "noop"

archival:
    history:
        state: "disabled"
    visibility:
        state: "disabled"