version: '3.8'

services:
  postgresql-temporal:
    image: postgres:14
    container_name: temporal-postgresql
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
      POSTGRES_DB: temporal
    ports:
      - "5434:5432"
    volumes:
      - temporal_postgres_data:/var/lib/postgresql/data
    networks:
      - temporal-network

  temporal:
    image: temporalio/auto-setup:latest
    container_name: temporal-server
    depends_on:
      - postgresql-temporal
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql-temporal
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
    ports:
      - "7233:7233"
    volumes:
      - ./temporal/dynamicconfig:/etc/temporal/config/dynamicconfig
    networks:
      - temporal-network

  temporal-admin-tools:
    image: temporalio/admin-tools:latest
    container_name: temporal-admin-tools
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    stdin_open: true
    tty: true
    networks:
      - temporal-network

  temporal-ui:
    image: temporalio/ui:latest
    container_name: temporal-ui
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    ports:
      - "8088:8080"
    networks:
      - temporal-network

  # SynapseDTE Temporal Worker - commented out for now as it depends on main db service
  # synapse-temporal-worker:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: synapse-temporal-worker
  #   command: python -m app.temporal.worker
  #   depends_on:
  #     - temporal
  #     - db
  #   environment:
  #     - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/synapse_dt
  #     - TEMPORAL_HOST=temporal:7233
  #     - TEMPORAL_NAMESPACE=default
  #     - PYTHONPATH=/app
  #   volumes:
  #     - ./app:/app/app
  #   networks:
  #     - temporal-network
  #     - synapse-network

networks:
  temporal-network:
    driver: bridge

volumes:
  temporal_postgres_data: