version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: synapse_user
      POSTGRES_PASSWORD: synapse_password
      POSTGRES_DB: synapse_dt
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend-clean:
    build: .
    command: uvicorn app.main_clean:app --host 0.0.0.0 --port 8001 --reload
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: postgresql+asyncpg://synapse_user:synapse_password@postgres:5432/synapse_dt
      SECRET_KEY: your-secret-key-here
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      USE_CLEAN_ARCHITECTURE: "true"
    depends_on:
      - postgres
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8001
    depends_on:
      - backend-clean
    volumes:
      - ./frontend/src:/app/src

  temporal:
    image: temporalio/temporal:latest
    ports:
      - "7233:7233"
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=synapse_user
      - POSTGRES_PWD=synapse_password
      - POSTGRES_SEEDS=postgres
    depends_on:
      - postgres

  temporal-ui:
    image: temporalio/ui:latest
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
    ports:
      - "8080:8080"
    depends_on:
      - temporal

volumes:
  postgres_data:
