-- Seed data for activity_definitions
-- Generated from: activity_definitions.json
-- Rows: 47

INSERT INTO activity_definitions (id, phase_name, activity_name, activity_code, description, activity_type, requires_backend_action, backend_endpoint, sequence_order, depends_on_activity_codes, button_text, success_message, instructions, can_skip, can_reset, auto_complete_on_condition, is_active, created_at, updated_at, created_by_id, updated_by_id, auto_complete, conditional_skip_rules) VALUES
(1, 'Planning', 'Start Planning Phase', 'start_planning', 'Initialize planning phase and set timeline', 'phase_start', TRUE, '/planning/cycles/{cycle_id}/reports/{report_id}/start', 1, '[]', 'Start Phase', 'Planning Phase Started', NULL, FALSE, TRUE, NULL, TRUE, '2025-07-11T18:53:24.714134', '2025-07-11T18:53:24.714134', NULL, NULL, TRUE, NULL);

INSERT INTO activity_definitions (id, phase_name, activity_name, activity_code, description, activity_type, requires_backend_action, backend_endpoint, sequence_order, depends_on_activity_codes, button_text, success_message, instructions, can_skip, can_reset, auto_complete_on_condition, is_active, created_at, updated_at, created_by_id, updated_by_id, auto_complete, conditional_skip_rules) VALUES
(2, 'Planning', 'Load Attributes', 'load_attributes', 'Load attributes from regulatory data dictionary', 'manual', FALSE, NULL, 2, '["start_planning"]', 'Start', 'Attributes loaded successfully', 'Click the "Load from Data Dictionary" button above to import attributes', FALSE, TRUE, NULL, TRUE, '2025-07-11T18:53:24.714134', '2025-07-11T18:53:24.714134', NULL, NULL, FALSE, NULL);

INSERT INTO activity_definitions (id, phase_name, activity_name, activity_code, description, activity_type, requires_backend_action, backend_endpoint, sequence_order, depends_on_activity_codes, button_text, success_message, instructions, can_skip, can_reset, auto_complete_on_condition, is_active, created_at, updated_at, created_by_id, updated_by_id, auto_complete, conditional_skip_rules) VALUES
(3, 'Planning', 'Review & Approve Attributes', 'review_attributes', 'Review and approve attributes for testing scope', 'manual', FALSE, NULL, 9, '["load_attributes"]', 'Start', 'Review and approve attributes in the table below', 'Review each attribute and click the approve button', FALSE, TRUE, NULL, TRUE, '2025-07-11T18:53:24.714134', '2025-07-11T18:53:24.714134', NULL, NULL, FALSE, NULL);

INSERT INTO activity_definitions (id, phase_name, activity_name, activity_code, description, activity_type, requires_backend_action, backend_endpoint, sequence_order, depends_on_activity_codes, button_text, success_message, instructions, can_skip, can_reset, auto_complete_on_condition, is_active, created_at, updated_at, created_by_id, updated_by_id, auto_complete, conditional_skip_rules) VALUES
(4, 'Planning', 'Complete Planning Phase', 'complete_planning', 'Finalize planning and proceed to scoping', 'phase_complete', TRUE, '/planning/cycles/{cycle_id}/reports/{report_id}/complete', 10, '["review_attributes"]', 'Complete Phase', 'Planning Phase Completed', NULL, FALSE, TRUE, NULL, TRUE, '2025-07-11T18:53:24.714134', '2025-07-11T18:53:24.714134', NULL, NULL, TRUE, NULL);

INSERT INTO activity_definitions (id, phase_name, activity_name, activity_code, description, activity_type, requires_backend_action, backend_endpoint, sequence_order, depends_on_activity_codes, button_text, success_message, instructions, can_skip, can_reset, auto_complete_on_condition, is_active, created_at, updated_at, created_by_id, updated_by_id, auto_complete, conditional_skip_rules) VALUES
(5, 'Scoping', 'Start Scoping Phase', 'start_scoping', 'Initialize scoping phase and load attributes', 'phase_start', TRUE, '/scoping/cycles/{cycle_id}/reports/{report_id}/start', 1, '[]', 'Start Phase', 'Scoping Phase Started', NULL, FALSE, TRUE, NULL, TRUE, '2025-07-11T18:53:24.714134', '2025-07-11T18:53:24.714134', NULL, NULL, TRUE, NULL);

INSERT INTO activity_definitions (id, phase_name, activity_name, activity_code, description, activity_type, requires_backend_action, backend_endpoint, sequence_order, depends_on_activity_codes, button_text, success_message, instructions, can_skip, can_reset, auto_complete_on_condition, is_active, created_at, updated_at, created_by_id, updated_by_id, auto_complete, conditional_skip_rules) VALUES
(6, 'Scoping', 'Generate LLM Recommendations', 'load_scoping_attributes', 'AI analyzes attributes and provides testing recommendations', 'automated', FALSE, NULL, 2, '["start_scoping"]', 'Generate Recommendations', 'LLM recommendations generated successfully', 'Click to generate AI-powered testing recommendations for all attributes', FALSE, FALSE, NULL, TRUE, '2025-07-11T18:53:24.714134', '2025-07-11T18:53:24.714134', NULL, NULL, FALSE, NULL);

INSERT INTO activity_definitions (id, phase_name, activity_name, activity_code, description, activity_type, requires_backend_action, backend_endpoint, sequence_order, depends_on_activity_codes, button_text, success_message, instructions, can_skip, can_reset, auto_complete_on_condition, is_active, created_at, updated_at, created_by_id, updated_by_id, auto_complete, conditional_skip_rules) VALUES
(7, 'Scoping', 'Make Scoping Decisions', 'make_scoping_decisions', 'Decide which attributes to include in testing', 'manual', FALSE, NULL, 3, '["load_scoping_attributes"]', 'Start', 'Use the Include/Exclude buttons to make scoping decisions', 'Mark each attribute as included or excluded from testing scope', FALSE, TRUE, NULL, TRUE, '2025-07-11T18:53:24.714134', '2025-07-11T18:53:24.714134', NULL, NULL, FALSE, NULL);

INSERT INTO activity_definitions (id, phase_name, activity_name, activity_code, description, activity_type, requires_backend_action, backend_endpoint, sequence_order, depends_on_activity_codes, button_text, success_message, instructions, can_skip, can_reset, auto_complete_on_condition, is_active, created_at, updated_at, created_by_id, updated_by_id, auto_complete, conditional_skip_rules) VALUES
(8, 'Scoping', 'Report Owner Approval', 'submit_scoping_approval', 'Report Owner reviews and approves the scoping decisions', 'manual', FALSE, NULL, 4, '["make_scoping_decisions"]', 'Submit to Report Owner', 'Submitted to Report Owner for approval', 'Click to submit the scoping decisions to the Report Owner for review and approval', FALSE, TRUE, NULL, TRUE, '2025-07-11T18:53:24.714134', '2025-07-11T18:53:24.714134', NULL, NULL, FALSE, NULL);

INSERT INTO activity_definitions (id, phase_name, activity_name, activity_code, description, activity_type, requires_backend_action, backend_endpoint, sequence_order, depends_on_activity_codes, button_text, success_message, instructions, can_skip, can_reset, auto_complete_on_condition, is_active, created_at, updated_at, created_by_id, updated_by_id, auto_complete, conditional_skip_rules) VALUES
(9, 'Scoping', 'Complete Scoping Phase', 'complete_scoping', 'Finalize scoping and proceed to next phase', 'phase_complete', TRUE, '/scoping/cycles/{cycle_id}/reports/{report_id}/complete', 5, '["submit_scoping_approval"]', 'Complete Phase', 'Scoping Phase Completed', NULL, FALSE, TRUE, NULL, TRUE, '2025-07-11T18:53:24.714134', '2025-07-11T18:53:24.714134', NULL, NULL, TRUE, NULL);

INSERT INTO activity_definitions (id, phase_name, activity_name, activity_code, description, activity_type, requires_backend_action, backend_endpoint, sequence_order, depends_on_activity_codes, button_text, success_message, instructions, can_skip, can_reset, auto_complete_on_condition, is_active, created_at, updated_at, created_by_id, updated_by_id, auto_complete, conditional_skip_rules) VALUES
(10, 'Sample Selection', 'Start Sample Selection', 'start_sample_selection', 'Initialize sample selection phase', 'phase_start', TRUE, '/sample-selection/cycles/{cycle_id}/reports/{report_id}/start', 1, '[]', 'Start Phase', 'Sample Selection Phase Started', NULL, FALSE, TRUE, NULL, TRUE, '2025-07-11T18:53:24.714134', '2025-07-11T18:53:24.714134', NULL, NULL, TRUE, NULL);

INSERT INTO activity_definitions (id, phase_name, activity_name, activity_code, description, activity_type, requires_backend_action, backend_endpoint, sequence_order, depends_on_activity_codes, button_text, success_message, instructions, can_skip, can_reset, auto_complete_on_condition, is_active, created_at, updated_at, created_by_id, updated_by_id, auto_complete, conditional_skip_rules) VALUES
(11, 'Sample Selection', 'Generate Samples', 'generate_samples', 'Generate sample sets for testing', 'manual', FALSE, NULL, 2, '["start_sample_selection"]', 'Start', 'Use the Generate Samples button to create sample sets', 'Click "Generate Samples" to create sample sets based on attributes', FALSE, TRUE, NULL, TRUE, '2025-07-11T18:53:24.714134', '2025-07-11T18:53:24.714134', NULL, NULL, FALSE, NULL);

INSERT INTO activity_definitions (id, phase_name, activity_name, activity_code, description, activity_type, requires_backend_action, backend_endpoint, sequence_order, depends_on_activity_codes, button_text, success_message, instructions, can_skip, can_reset, auto_complete_on_condition, is_active, created_at, updated_at, created_by_id, updated_by_id, auto_complete, conditional_skip_rules) VALUES
(12, 'Sample Selection', 'Review Samples', 'review_samples', 'Review generated sample sets', 'manual', FALSE, NULL, 3, '["generate_samples"]', 'Start', 'Review the generated samples in the table below', 'Review each sample set for accuracy and completeness', FALSE, TRUE, NULL, TRUE, '2025-07-11T18:53:24.714134', '2025-07-11T18:53:24.714134', NULL, NULL, FALSE, NULL);

INSERT INTO activity_definitions (id, phase_name, activity_name, activity_code, description, activity_type, requires_backend_action, backend_endpoint, sequence_order, depends_on_activity_codes, button_text, success_message, instructions, can_skip, can_reset, auto_complete_on_condition, is_active, created_at, updated_at, created_by_id, updated_by_id, auto_complete, conditional_skip_rules) VALUES
(13, 'Sample Selection', 'Approve Samples', 'approve_samples', 'Approve sample sets for testing', 'manual', FALSE, NULL, 4, '["review_samples"]', 'Start', 'Use the Approve button to approve sample sets', 'Click the approve button for each sample set', FALSE, TRUE, NULL, TRUE, '2025-07-11T18:53:24.714134', '2025-07-11T18:53:24.714134', NULL, NULL, FALSE, NULL);

INSERT INTO activity_definitions (id, phase_name, activity_name, activity_code, description, activity_type, requires_backend_action, backend_endpoint, sequence_order, depends_on_activity_codes, button_text, success_message, instructions, can_skip, can_reset, auto_complete_on_condition, is_active, created_at, updated_at, created_by_id, updated_by_id, auto_complete, conditional_skip_rules) VALUES
(14, 'Sample Selection', 'Complete Sample Selection', 'complete_sample_selection', 'Finalize sample selection', 'phase_complete', TRUE, '/sample-selection/cycles/{cycle_id}/reports/{report_id}/complete', 5, '["approve_samples"]', 'Complete Phase', 'Sample Selection Phase Completed', NULL, FALSE, TRUE, NULL, TRUE, '2025-07-11T18:53:24.714134', '2025-07-11T18:53:24.714134', NULL, NULL, TRUE, NULL);

INSERT INTO activity_definitions (id, phase_name, activity_name, activity_code, description, activity_type, requires_backend_action, backend_endpoint, sequence_order, depends_on_activity_codes, button_text, success_message, instructions, can_skip, can_reset, auto_complete_on_condition, is_active, created_at, updated_at, created_by_id, updated_by_id, auto_complete, conditional_skip_rules) VALUES
(19, 'Test Execution', 'Start Test Execution Phase', 'start_test_execution', 'Initialize test execution phase', 'phase_start', TRUE, '/test-execution/cycles/{cycle_id}/reports/{report_id}/start', 1, '[]', 'Start Phase', 'Test Execution Phase Started', NULL, FALSE, TRUE, NULL, TRUE, '2025-07-11T19:58:42.066594', '2025-07-11T19:58:42.066594', NULL, NULL, FALSE, NULL);

INSERT INTO activity_definitions (id, phase_name, activity_name, activity_code, description, activity_type, requires_backend_action, backend_endpoint, sequence_order, depends_on_activity_codes, button_text, success_message, instructions, can_skip, can_reset, auto_complete_on_condition, is_active, created_at, updated_at, created_by_id, updated_by_id, auto_complete, conditional_skip_rules) VALUES
(20, 'Test Execution', 'Load Test Cases', 'load_test_cases', 'Load test cases from Request Info phase', 'manual', FALSE, NULL, 2, '["start_test_execution"]', 'Load Test Cases', 'Test cases loaded successfully', 'Test cases are automatically loaded from Request Info phase', FALSE, TRUE, NULL, TRUE, '2025-07-11T19:58:42.066594', '2025-07-11T19:58:42.066594', NULL, NULL, FALSE, NULL);

INSERT INTO activity_definitions (id, phase_name, activity_name, activity_code, description, activity_type, requires_backend_action, backend_endpoint, sequence_order, depends_on_activity_codes, button_text, success_message, instructions, can_skip, can_reset, auto_complete_on_condition, is_active, created_at, updated_at, created_by_id, updated_by_id, auto_complete, conditional_skip_rules) VALUES
(21, 'Test Execution', 'Execute Tests', 'execute_tests', 'Execute document and database tests', 'manual', FALSE, NULL, 3, '["load_test_cases"]', 'Execute Tests', 'Tests executed successfully', 'Use the test execution interface to run tests', FALSE, TRUE, NULL, TRUE, '2025-07-11T19:58:42.066594', '2025-07-11T19:58:42.066594', NULL, NULL, FALSE, NULL);

INSERT INTO activity_definitions (id, phase_name, activity_name, activity_code, description, activity_type, requires_backend_action, backend_endpoint, sequence_order, depends_on_activity_codes, button_text, success_message, instructions, can_skip, can_reset, auto_complete_on_condition, is_active, created_at, updated_at, created_by_id, updated_by_id, auto_complete, conditional_skip_rules) VALUES
(22, 'Test Execution', 'Complete Test Execution', 'complete_test_execution', 'Complete test execution phase', 'phase_complete', TRUE, '/test-execution/cycles/{cycle_id}/reports/{report_id}/complete', 4, '["execute_tests"]', 'Complete Phase', 'Test Execution Phase Completed', NULL, FALSE, FALSE, NULL, TRUE, '2025-07-11T19:58:42.066594', '2025-07-11T19:58:42.066594', NULL, NULL, FALSE, NULL);

INSERT INTO activity_definitions (id, phase_name, activity_name, activity_code, description, activity_type, requires_backend_action, backend_endpoint, sequence_order, depends_on_activity_codes, button_text, success_message, instructions, can_skip, can_reset, auto_complete_on_condition, is_active, created_at, updated_at, created_by_id, updated_by_id, auto_complete, conditional_skip_rules) VALUES
(23, 'Observations', 'Start Observations Phase', 'start_observations', 'Initialize observations phase', 'phase_start', TRUE, '/observations/cycles/{cycle_id}/reports/{report_id}/start', 1, '[]', 'Start Phase', 'Observations Phase Started', NULL, FALSE, TRUE, NULL, TRUE, '2025-07-11T19:58:42.066594', '2025-07-11T19:58:42.066594', NULL, NULL, FALSE, NULL);

INSERT INTO activity_definitions (id, phase_name, activity_name, activity_code, description, activity_type, requires_backend_action, backend_endpoint, sequence_order, depends_on_activity_codes, button_text, success_message, instructions, can_skip, can_reset, auto_complete_on_condition, is_active, created_at, updated_at, created_by_id, updated_by_id, auto_complete, conditional_skip_rules) VALUES
(24, 'Observations', 'Review Test Results', 'review_test_results', 'Review failed test cases and create observations', 'manual', FALSE, NULL, 2, '["start_observations"]', 'Review Results', 'Test results reviewed', 'Review failed test cases and create observations as needed', FALSE, TRUE, NULL, TRUE, '2025-07-11T19:58:42.066594', '2025-07-11T19:58:42.066594', NULL, NULL, FALSE, NULL);

INSERT INTO activity_definitions (id, phase_name, activity_name, activity_code, description, activity_type, requires_backend_action, backend_endpoint, sequence_order, depends_on_activity_codes, button_text, success_message, instructions, can_skip, can_reset, auto_complete_on_condition, is_active, created_at, updated_at, created_by_id, updated_by_id, auto_complete, conditional_skip_rules) VALUES
(25, 'Observations', 'Manage Observations', 'manage_observations', 'Create, update, and approve observations', 'manual', FALSE, NULL, 3, '["review_test_results"]', 'Manage Observations', 'Observations managed successfully', 'Use the observations interface to manage observations', FALSE, TRUE, NULL, TRUE, '2025-07-11T19:58:42.066594', '2025-07-11T19:58:42.066594', NULL, NULL, FALSE, NULL);

INSERT INTO activity_definitions (id, phase_name, activity_name, activity_code, description, activity_type, requires_backend_action, backend_endpoint, sequence_order, depends_on_activity_codes, button_text, success_message, instructions, can_skip, can_reset, auto_complete_on_condition, is_active, created_at, updated_at, created_by_id, updated_by_id, auto_complete, conditional_skip_rules) VALUES
(26, 'Observations', 'Complete Observations', 'complete_observations', 'Complete observations phase', 'phase_complete', TRUE, '/observations/cycles/{cycle_id}/reports/{report_id}/complete', 4, '["manage_observations"]', 'Complete Phase', 'Observations Phase Completed', NULL, FALSE, FALSE, NULL, TRUE, '2025-07-11T19:58:42.066594', '2025-07-11T19:58:42.066594', NULL, NULL, FALSE, NULL);

INSERT INTO activity_definitions (id, phase_name, activity_name, activity_code, description, activity_type, requires_backend_action, backend_endpoint, sequence_order, depends_on_activity_codes, button_text, success_message, instructions, can_skip, can_reset, auto_complete_on_condition, is_active, created_at, updated_at, created_by_id, updated_by_id, auto_complete, conditional_skip_rules) VALUES
(27, 'Finalize Test Report', 'Start Finalize Phase', 'start_finalize', 'Initialize report finalization phase', 'phase_start', TRUE, '/test-report/cycles/{cycle_id}/reports/{report_id}/start', 1, '[]', 'Start Phase', 'Finalize Phase Started', NULL, FALSE, TRUE, NULL, TRUE, '2025-07-11T19:58:42.066594', '2025-07-11T19:58:42.066594', NULL, NULL, FALSE, NULL);

INSERT INTO activity_definitions (id, phase_name, activity_name, activity_code, description, activity_type, requires_backend_action, backend_endpoint, sequence_order, depends_on_activity_codes, button_text, success_message, instructions, can_skip, can_reset, auto_complete_on_condition, is_active, created_at, updated_at, created_by_id, updated_by_id, auto_complete, conditional_skip_rules) VALUES
(28, 'Finalize Test Report', 'Generate Report', 'generate_report', 'Generate final test report', 'manual', TRUE, '/test-report/cycles/{cycle_id}/reports/{report_id}/generate', 2, '["start_finalize"]', 'Generate Report', 'Report generated successfully', 'Click to generate the final test report', FALSE, TRUE, NULL, TRUE, '2025-07-11T19:58:42.066594', '2025-07-11T19:58:42.066594', NULL, NULL, FALSE, NULL);

INSERT INTO activity_definitions (id, phase_name, activity_name, activity_code, description, activity_type, requires_backend_action, backend_endpoint, sequence_order, depends_on_activity_codes, button_text, success_message, instructions, can_skip, can_reset, auto_complete_on_condition, is_active, created_at, updated_at, created_by_id, updated_by_id, auto_complete, conditional_skip_rules) VALUES
(29, 'Finalize Test Report', 'Review Report', 'review_report', 'Review the generated test report', 'manual', FALSE, NULL, 3, '["generate_report"]', 'Review Report', 'Report reviewed', 'Review the generated report for completeness and accuracy', FALSE, TRUE, NULL, TRUE, '2025-07-11T19:58:42.066594', '2025-07-11T19:58:42.066594', NULL, NULL, FALSE, NULL);

INSERT INTO activity_definitions (id, phase_name, activity_name, activity_code, description, activity_type, requires_backend_action, backend_endpoint, sequence_order, depends_on_activity_codes, button_text, success_message, instructions, can_skip, can_reset, auto_complete_on_condition, is_active, created_at, updated_at, created_by_id, updated_by_id, auto_complete, conditional_skip_rules) VALUES
(30, 'Finalize Test Report', 'Approve Report', 'approve_report', 'Approve the final test report', 'manual', TRUE, '/test-report/cycles/{cycle_id}/reports/{report_id}/approve', 4, '["review_report"]', 'Approve Report', 'Report approved successfully', 'Approve the final test report', FALSE, FALSE, NULL, TRUE, '2025-07-11T19:58:42.066594', '2025-07-11T19:58:42.066594', NULL, NULL, FALSE, NULL);

INSERT INTO activity_definitions (id, phase_name, activity_name, activity_code, description, activity_type, requires_backend_action, backend_endpoint, sequence_order, depends_on_activity_codes, button_text, success_message, instructions, can_skip, can_reset, auto_complete_on_condition, is_active, created_at, updated_at, created_by_id, updated_by_id, auto_complete, conditional_skip_rules) VALUES
(31, 'Finalize Test Report', 'Complete Report', 'complete_report', 'Complete the test report phase', 'phase_complete', TRUE, '/test-report/cycles/{cycle_id}/reports/{report_id}/complete', 5, '["approve_report"]', 'Complete Phase', 'Test Report Finalized', NULL, FALSE, FALSE, NULL, TRUE, '2025-07-11T19:58:42.066594', '2025-07-11T19:58:42.066594', NULL, NULL, FALSE, NULL);

INSERT INTO activity_definitions (id, phase_name, activity_name, activity_code, description, activity_type, requires_backend_action, backend_endpoint, sequence_order, depends_on_activity_codes, button_text, success_message, instructions, can_skip, can_reset, auto_complete_on_condition, is_active, created_at, updated_at, created_by_id, updated_by_id, auto_complete, conditional_skip_rules) VALUES
(32, 'Data Profiling', 'Start Data Profiling Phase', 'start_data_profiling', 'Initiate the data profiling phase', 'phase_start', TRUE, NULL, 1, '[]', 'Start Phase', 'Data Profiling phase started successfully', 'Click to begin the data profiling phase', FALSE, FALSE, NULL, TRUE, '2025-07-11T21:02:36.206058', '2025-07-11T21:02:36.206058', NULL, NULL, FALSE, NULL);

INSERT INTO activity_definitions (id, phase_name, activity_name, activity_code, description, activity_type, requires_backend_action, backend_endpoint, sequence_order, depends_on_activity_codes, button_text, success_message, instructions, can_skip, can_reset, auto_complete_on_condition, is_active, created_at, updated_at, created_by_id, updated_by_id, auto_complete, conditional_skip_rules) VALUES
(33, 'Data Profiling', 'Upload Data Files', 'upload_data_files', 'Upload data files for profiling', 'manual', FALSE, NULL, 2, '["start_data_profiling"]', 'Mark Complete', 'Data files uploaded successfully', 'Upload the data files that need to be profiled', FALSE, TRUE, NULL, TRUE, '2025-07-11T21:02:36.206058', '2025-07-11T21:02:36.206058', NULL, NULL, FALSE, NULL);

INSERT INTO activity_definitions (id, phase_name, activity_name, activity_code, description, activity_type, requires_backend_action, backend_endpoint, sequence_order, depends_on_activity_codes, button_text, success_message, instructions, can_skip, can_reset, auto_complete_on_condition, is_active, created_at, updated_at, created_by_id, updated_by_id, auto_complete, conditional_skip_rules) VALUES
(34, 'Data Profiling', 'Generate LLM Data Profiling Rules', 'generate_profile', 'AI analyzes attributes and generates data profiling rules', 'manual', TRUE, NULL, 3, '["upload_data_files"]', 'Generate Profile', 'Data profile generated successfully', 'Use the Generate Profile button to analyze the uploaded data', FALSE, TRUE, NULL, TRUE, '2025-07-11T21:02:36.206058', '2025-07-11T21:02:36.206058', NULL, NULL, FALSE, NULL);

INSERT INTO activity_definitions (id, phase_name, activity_name, activity_code, description, activity_type, requires_backend_action, backend_endpoint, sequence_order, depends_on_activity_codes, button_text, success_message, instructions, can_skip, can_reset, auto_complete_on_condition, is_active, created_at, updated_at, created_by_id, updated_by_id, auto_complete, conditional_skip_rules) VALUES
(35, 'Data Profiling', 'Review Profiling Rules', 'review_rules', 'Review and approve generated profiling rules', 'manual', FALSE, NULL, 4, '["generate_profile"]', 'Mark Complete', 'Profiling rules reviewed', 'Review the generated profiling rules and approve them', FALSE, TRUE, NULL, TRUE, '2025-07-11T21:02:36.206058', '2025-07-11T21:02:36.206058', NULL, NULL, FALSE, NULL);

INSERT INTO activity_definitions (id, phase_name, activity_name, activity_code, description, activity_type, requires_backend_action, backend_endpoint, sequence_order, depends_on_activity_codes, button_text, success_message, instructions, can_skip, can_reset, auto_complete_on_condition, is_active, created_at, updated_at, created_by_id, updated_by_id, auto_complete, conditional_skip_rules) VALUES
(36, 'Data Profiling', 'Execute Data Profiling', 'execute_profiling', 'Execute the approved profiling rules', 'manual', TRUE, NULL, 6, '["review_rules"]', 'Execute Profiling', 'Data profiling executed successfully', 'Run the profiling rules against the data', FALSE, TRUE, NULL, TRUE, '2025-07-11T21:02:36.206058', '2025-07-11T21:02:36.206058', NULL, NULL, FALSE, NULL);

INSERT INTO activity_definitions (id, phase_name, activity_name, activity_code, description, activity_type, requires_backend_action, backend_endpoint, sequence_order, depends_on_activity_codes, button_text, success_message, instructions, can_skip, can_reset, auto_complete_on_condition, is_active, created_at, updated_at, created_by_id, updated_by_id, auto_complete, conditional_skip_rules) VALUES
(37, 'Data Profiling', 'Complete Data Profiling Phase', 'complete_data_profiling', 'Complete the data profiling phase', 'phase_complete', TRUE, NULL, 7, '["execute_profiling"]', 'Complete Phase', 'Data Profiling phase completed successfully', 'Complete the data profiling phase', FALSE, FALSE, NULL, TRUE, '2025-07-11T21:02:36.206058', '2025-07-11T21:02:36.206058', NULL, NULL, FALSE, NULL);

INSERT INTO activity_definitions (id, phase_name, activity_name, activity_code, description, activity_type, requires_backend_action, backend_endpoint, sequence_order, depends_on_activity_codes, button_text, success_message, instructions, can_skip, can_reset, auto_complete_on_condition, is_active, created_at, updated_at, created_by_id, updated_by_id, auto_complete, conditional_skip_rules) VALUES
(40, 'Request Info', 'Start Request Info Phase', 'start_request_info', 'Initiate the request for information phase', 'phase_start', TRUE, NULL, 1, '[]', 'Start Phase', 'Request Info phase started successfully', 'Click to begin the request for information phase', FALSE, FALSE, NULL, TRUE, '2025-07-11T21:04:50.619741', '2025-07-11T21:04:50.619741', NULL, NULL, FALSE, NULL);

INSERT INTO activity_definitions (id, phase_name, activity_name, activity_code, description, activity_type, requires_backend_action, backend_endpoint, sequence_order, depends_on_activity_codes, button_text, success_message, instructions, can_skip, can_reset, auto_complete_on_condition, is_active, created_at, updated_at, created_by_id, updated_by_id, auto_complete, conditional_skip_rules) VALUES
(41, 'Request Info', 'Create Test Cases', 'create_test_cases', 'Create test cases for data collection', 'manual_with_backend', TRUE, NULL, 2, '["start_request_info"]', 'Create Test Cases', 'Test cases created successfully', 'Test cases will be automatically created when you start this activity', FALSE, TRUE, NULL, TRUE, '2025-07-11T21:04:50.619741', '2025-07-11T21:04:50.619741', NULL, NULL, FALSE, NULL);

INSERT INTO activity_definitions (id, phase_name, activity_name, activity_code, description, activity_type, requires_backend_action, backend_endpoint, sequence_order, depends_on_activity_codes, button_text, success_message, instructions, can_skip, can_reset, auto_complete_on_condition, is_active, created_at, updated_at, created_by_id, updated_by_id, auto_complete, conditional_skip_rules) VALUES
(42, 'Request Info', 'Notify Data Providers', 'notify_data_providers', 'Send notifications to data providers', 'manual', TRUE, NULL, 3, '["create_test_cases"]', 'Send Notifications', 'Notifications sent successfully', 'Send email notifications to data providers', FALSE, TRUE, NULL, TRUE, '2025-07-11T21:04:50.619741', '2025-07-11T21:04:50.619741', NULL, NULL, FALSE, NULL);

INSERT INTO activity_definitions (id, phase_name, activity_name, activity_code, description, activity_type, requires_backend_action, backend_endpoint, sequence_order, depends_on_activity_codes, button_text, success_message, instructions, can_skip, can_reset, auto_complete_on_condition, is_active, created_at, updated_at, created_by_id, updated_by_id, auto_complete, conditional_skip_rules) VALUES
(43, 'Request Info', 'Collect Documents', 'collect_documents', 'Collect supporting documents from data providers', 'manual', FALSE, NULL, 4, '["notify_data_providers"]', 'Mark Complete', 'Documents collected successfully', 'Monitor and collect documents submitted by data providers', FALSE, TRUE, NULL, TRUE, '2025-07-11T21:04:50.619741', '2025-07-11T21:04:50.619741', NULL, NULL, FALSE, NULL);

INSERT INTO activity_definitions (id, phase_name, activity_name, activity_code, description, activity_type, requires_backend_action, backend_endpoint, sequence_order, depends_on_activity_codes, button_text, success_message, instructions, can_skip, can_reset, auto_complete_on_condition, is_active, created_at, updated_at, created_by_id, updated_by_id, auto_complete, conditional_skip_rules) VALUES
(44, 'Request Info', 'Review Submissions', 'review_submissions', 'Review all submitted documents', 'manual', FALSE, NULL, 5, '["collect_documents"]', 'Mark Complete', 'Submissions reviewed successfully', 'Review completeness of submitted documents', FALSE, TRUE, NULL, TRUE, '2025-07-11T21:04:50.619741', '2025-07-11T21:04:50.619741', NULL, NULL, FALSE, NULL);

INSERT INTO activity_definitions (id, phase_name, activity_name, activity_code, description, activity_type, requires_backend_action, backend_endpoint, sequence_order, depends_on_activity_codes, button_text, success_message, instructions, can_skip, can_reset, auto_complete_on_condition, is_active, created_at, updated_at, created_by_id, updated_by_id, auto_complete, conditional_skip_rules) VALUES
(45, 'Request Info', 'Complete Request Info Phase', 'complete_request_info', 'Complete the request for information phase', 'phase_complete', TRUE, NULL, 6, '["review_submissions"]', 'Complete Phase', 'Request Info phase completed successfully', 'Complete the request for information phase', FALSE, FALSE, NULL, TRUE, '2025-07-11T21:04:50.619741', '2025-07-11T21:04:50.619741', NULL, NULL, FALSE, NULL);

INSERT INTO activity_definitions (id, phase_name, activity_name, activity_code, description, activity_type, requires_backend_action, backend_endpoint, sequence_order, depends_on_activity_codes, button_text, success_message, instructions, can_skip, can_reset, auto_complete_on_condition, is_active, created_at, updated_at, created_by_id, updated_by_id, auto_complete, conditional_skip_rules) VALUES
(46, 'Data Provider ID', 'Start Data Provider ID Phase', 'start_data_provider_id', 'Initiate the data provider identification phase', 'phase_start', TRUE, NULL, 1, '[]', 'Start Phase', 'Data Provider ID phase started successfully', 'Click to begin identifying data providers', FALSE, FALSE, NULL, TRUE, '2025-07-11T21:05:14.543813', '2025-07-11T21:05:14.543813', NULL, NULL, FALSE, NULL);

INSERT INTO activity_definitions (id, phase_name, activity_name, activity_code, description, activity_type, requires_backend_action, backend_endpoint, sequence_order, depends_on_activity_codes, button_text, success_message, instructions, can_skip, can_reset, auto_complete_on_condition, is_active, created_at, updated_at, created_by_id, updated_by_id, auto_complete, conditional_skip_rules) VALUES
(48, 'Data Provider ID', 'Assign Data Providers', 'assign_data_providers', 'Assign data providers to attributes', 'manual', FALSE, NULL, 2, '["start_data_provider_id"]', 'Mark Complete', 'Data providers assigned successfully', 'Assign a data provider to each attribute', FALSE, TRUE, NULL, TRUE, '2025-07-11T21:05:14.543813', '2025-07-11T21:05:14.543813', NULL, NULL, FALSE, NULL);

INSERT INTO activity_definitions (id, phase_name, activity_name, activity_code, description, activity_type, requires_backend_action, backend_endpoint, sequence_order, depends_on_activity_codes, button_text, success_message, instructions, can_skip, can_reset, auto_complete_on_condition, is_active, created_at, updated_at, created_by_id, updated_by_id, auto_complete, conditional_skip_rules) VALUES
(49, 'Data Provider ID', 'Review Provider Assignments', 'review_provider_assignments', 'Review all data provider assignments', 'manual', FALSE, NULL, 2, '["assign_data_providers"]', 'Mark Complete', 'Assignments reviewed successfully', 'Review and confirm all data provider assignments', FALSE, TRUE, NULL, TRUE, '2025-07-11T21:05:14.543813', '2025-07-11T21:05:14.543813', NULL, NULL, FALSE, NULL);

INSERT INTO activity_definitions (id, phase_name, activity_name, activity_code, description, activity_type, requires_backend_action, backend_endpoint, sequence_order, depends_on_activity_codes, button_text, success_message, instructions, can_skip, can_reset, auto_complete_on_condition, is_active, created_at, updated_at, created_by_id, updated_by_id, auto_complete, conditional_skip_rules) VALUES
(50, 'Data Provider ID', 'Complete Data Provider ID Phase', 'complete_data_provider_id', 'Complete the data provider identification phase', 'phase_complete', TRUE, NULL, 3, '["review_provider_assignments"]', 'Complete Phase', 'Data Provider ID phase completed successfully', 'Complete the data provider identification phase', FALSE, FALSE, NULL, TRUE, '2025-07-11T21:05:14.543813', '2025-07-11T21:05:14.543813', NULL, NULL, FALSE, NULL);

INSERT INTO activity_definitions (id, phase_name, activity_name, activity_code, description, activity_type, requires_backend_action, backend_endpoint, sequence_order, depends_on_activity_codes, button_text, success_message, instructions, can_skip, can_reset, auto_complete_on_condition, is_active, created_at, updated_at, created_by_id, updated_by_id, auto_complete, conditional_skip_rules) VALUES
(51, 'Planning', 'Add Data Source', 'add_data_source', 'Configure data source connections for the report', 'manual', TRUE, NULL, 3, '["load_attributes"]', 'Start', 'Data source configured successfully', 'Configure the data source connection for this report. You can set up database connections, file locations, or API endpoints that will be used for data validation and testing.', TRUE, TRUE, NULL, TRUE, '2025-07-11T21:59:42.962446', '2025-07-11T22:17:02.227197', NULL, NULL, FALSE, NULL);

INSERT INTO activity_definitions (id, phase_name, activity_name, activity_code, description, activity_type, requires_backend_action, backend_endpoint, sequence_order, depends_on_activity_codes, button_text, success_message, instructions, can_skip, can_reset, auto_complete_on_condition, is_active, created_at, updated_at, created_by_id, updated_by_id, auto_complete, conditional_skip_rules) VALUES
(52, 'Planning', 'Map PDEs', 'map_pdes', 'Map Process Data Elements to report attributes and classify by risk/security', 'manual', TRUE, NULL, 4, '["load_attributes"]', 'Start', 'PDEs mapped and classified successfully', 'Map Process Data Elements (PDEs) to the loaded report attributes and classify them based on information security requirements. The system will automatically suggest security classifications and risk levels.', TRUE, TRUE, NULL, TRUE, '2025-07-11T21:59:42.964995', '2025-07-21T15:17:49.188815', NULL, NULL, FALSE, NULL);

INSERT INTO activity_definitions (id, phase_name, activity_name, activity_code, description, activity_type, requires_backend_action, backend_endpoint, sequence_order, depends_on_activity_codes, button_text, success_message, instructions, can_skip, can_reset, auto_complete_on_condition, is_active, created_at, updated_at, created_by_id, updated_by_id, auto_complete, conditional_skip_rules) VALUES
(53, 'Planning', 'Classify PDEs', 'classify_pdes', 'DEPRECATED: Classification now happens automatically during PDE mapping', 'manual', TRUE, NULL, 5, '["load_attributes", "map_pdes"]', 'Start', 'PDEs classified successfully', 'Classify Process Data Elements by criticality, risk level, and regulatory requirements. AI will assist in identifying high-risk and compliance-critical elements.', TRUE, TRUE, NULL, FALSE, '2025-07-11T21:59:42.965453', '2025-07-21T15:17:49.188815', NULL, NULL, FALSE, NULL);

INSERT INTO activity_definitions (id, phase_name, activity_name, activity_code, description, activity_type, requires_backend_action, backend_endpoint, sequence_order, depends_on_activity_codes, button_text, success_message, instructions, can_skip, can_reset, auto_complete_on_condition, is_active, created_at, updated_at, created_by_id, updated_by_id, auto_complete, conditional_skip_rules) VALUES
(54, 'Data Profiling', 'Report Owner Rule Approval', 'report_owner_rule_approval', 'Report Owner reviews and approves/rejects data profiling rules', 'approval', FALSE, NULL, 5, '[]', 'Review Rules', 'Report Owner approval in progress', NULL, FALSE, TRUE, NULL, TRUE, '2025-07-16T05:39:37.594024', '2025-07-16T05:39:37.594024', NULL, NULL, FALSE, NULL);

