-- Seed data for cycle_report_planning_data_sources
-- Generated from: cycle_report_planning_data_sources.json
-- Rows: 10

INSERT INTO cycle_report_planning_data_sources (id, name, description, source_type, is_active, connection_config, auth_type, auth_config, refresh_schedule, last_sync_at, last_sync_status, last_sync_message, validation_rules, created_at, updated_at, created_by_id, updated_by_id, phase_id, schema_summary) VALUES
(7, 'DS - 14M D1', 'DS - 14M D1', 'POSTGRESQL', TRUE, '{"host": "localhost", "port": "5432", "database": "synapse_dt", "schema": "public", "table_name": "fry14m_scheduled1_data"}', 'basic', '{"username": "synapse_user", "password": "synapse_password"}', '', NULL, 'never', NULL, '{}', '2025-07-20T14:56:13.694069', '2025-07-20T14:56:13.694069', 3, 3, 465, NULL);

INSERT INTO cycle_report_planning_data_sources (id, name, description, source_type, is_active, connection_config, auth_type, auth_config, refresh_schedule, last_sync_at, last_sync_status, last_sync_message, validation_rules, created_at, updated_at, created_by_id, updated_by_id, phase_id, schema_summary) VALUES
(8, 'DS - 14M D1', 'DS - 14M D1', 'POSTGRESQL', TRUE, '{"host": "localhost", "port": "5432", "database": "synapse_dt", "schema": "public", "table_name": "fry14m_scheduled1_data"}', 'basic', '{"username": "synapse_user", "password": "synapse_password"}', '', NULL, 'never', NULL, '{}', '2025-07-22T16:55:26.141047', '2025-07-22T16:55:26.141047', 3, 3, 474, NULL);

INSERT INTO cycle_report_planning_data_sources (id, name, description, source_type, is_active, connection_config, auth_type, auth_config, refresh_schedule, last_sync_at, last_sync_status, last_sync_message, validation_rules, created_at, updated_at, created_by_id, updated_by_id, phase_id, schema_summary) VALUES
(9, 'FRY14M Data Source', 'Data source for Current Credit limit from fry14m_scheduled1_data', 'POSTGRESQL', TRUE, '{"type": "PostgreSQL", "host": "localhost", "port": 5432, "database": "synapse_dt", "schema": "public", "table": "fry14m_scheduled1_data", "columns": {"Current Credit limit": "current_credit_limit", "Customer ID": "customer_id", "Credit Card Type": "credit_card_type", "State": "state"}}', NULL, '{"username": "synapse_user", "password": "synapse_password"}', NULL, NULL, NULL, NULL, NULL, '2025-07-27T13:38:18.353608', '2025-07-27T13:38:18.353608', 6, 6, 470, NULL);

INSERT INTO cycle_report_planning_data_sources (id, name, description, source_type, is_active, connection_config, auth_type, auth_config, refresh_schedule, last_sync_at, last_sync_status, last_sync_message, validation_rules, created_at, updated_at, created_by_id, updated_by_id, phase_id, schema_summary) VALUES
(10, 'FRY14M API Test Data Source', 'Updated description via API test', 'POSTGRESQL', TRUE, '{"host": "localhost", "port": 5432, "database": "synapse_dt", "schema_name": "public", "table": "fry14m_scheduled1_data"}', NULL, '{"username": "synapse_user", "password": "synapse_password"}', NULL, NULL, NULL, NULL, NULL, '2025-07-27T15:04:29.486534', '2025-07-27T19:04:29.575605', 6, 6, 470, NULL);

INSERT INTO cycle_report_planning_data_sources (id, name, description, source_type, is_active, connection_config, auth_type, auth_config, refresh_schedule, last_sync_at, last_sync_status, last_sync_message, validation_rules, created_at, updated_at, created_by_id, updated_by_id, phase_id, schema_summary) VALUES
(11, 'FRY14M API Test Data Source', 'Updated description via API test', 'POSTGRESQL', TRUE, '{"host": "localhost", "port": 5432, "database": "synapse_dt", "schema_name": "public", "table": "fry14m_scheduled1_data"}', NULL, '{"username": "synapse_user", "password": "synapse_password"}', NULL, NULL, NULL, NULL, NULL, '2025-07-27T15:05:29.401970', '2025-07-27T19:05:29.503580', 6, 6, 470, NULL);

INSERT INTO cycle_report_planning_data_sources (id, name, description, source_type, is_active, connection_config, auth_type, auth_config, refresh_schedule, last_sync_at, last_sync_status, last_sync_message, validation_rules, created_at, updated_at, created_by_id, updated_by_id, phase_id, schema_summary) VALUES
(12, 'FRY14M API Test Data Source', 'Updated description via API test', 'POSTGRESQL', TRUE, '{"host": "localhost", "port": 5432, "database": "synapse_dt", "schema_name": "public", "table": "fry14m_scheduled1_data"}', NULL, '{"username": "synapse_user", "password": "synapse_password"}', NULL, NULL, NULL, NULL, NULL, '2025-07-27T15:05:51.539366', '2025-07-27T19:05:51.635443', 6, 6, 470, NULL);

INSERT INTO cycle_report_planning_data_sources (id, name, description, source_type, is_active, connection_config, auth_type, auth_config, refresh_schedule, last_sync_at, last_sync_status, last_sync_message, validation_rules, created_at, updated_at, created_by_id, updated_by_id, phase_id, schema_summary) VALUES
(13, 'FRY14M API Test Data Source', 'Updated description via API test', 'POSTGRESQL', TRUE, '{"host": "localhost", "port": 5432, "database": "synapse_dt", "schema_name": "public", "table": "fry14m_scheduled1_data"}', NULL, '{"username": "synapse_user", "password": "synapse_password"}', NULL, NULL, NULL, NULL, NULL, '2025-07-27T15:06:41.597103', '2025-07-27T19:06:41.698985', 6, 6, 470, NULL);

INSERT INTO cycle_report_planning_data_sources (id, name, description, source_type, is_active, connection_config, auth_type, auth_config, refresh_schedule, last_sync_at, last_sync_status, last_sync_message, validation_rules, created_at, updated_at, created_by_id, updated_by_id, phase_id, schema_summary) VALUES
(14, 'FRY14M API Test Data Source', 'Updated description via API test', 'POSTGRESQL', TRUE, '{"host": "localhost", "port": 5432, "database": "synapse_dt", "schema_name": "public", "table": "fry14m_scheduled1_data"}', NULL, '{"username": "synapse_user", "password": "synapse_password"}', NULL, NULL, NULL, NULL, NULL, '2025-07-27T15:07:26.858564', '2025-07-27T19:07:26.952812', 6, 6, 470, NULL);

INSERT INTO cycle_report_planning_data_sources (id, name, description, source_type, is_active, connection_config, auth_type, auth_config, refresh_schedule, last_sync_at, last_sync_status, last_sync_message, validation_rules, created_at, updated_at, created_by_id, updated_by_id, phase_id, schema_summary) VALUES
(15, 'FRY14M API Test Data Source', 'Updated description via API test', 'POSTGRESQL', TRUE, '{"host": "localhost", "port": 5432, "database": "synapse_dt", "schema_name": "public", "table": "fry14m_scheduled1_data"}', NULL, '{"username": "synapse_user", "password": "synapse_password"}', NULL, NULL, NULL, NULL, NULL, '2025-07-27T15:07:50.603945', '2025-07-27T19:07:50.689608', 6, 6, 470, NULL);

INSERT INTO cycle_report_planning_data_sources (id, name, description, source_type, is_active, connection_config, auth_type, auth_config, refresh_schedule, last_sync_at, last_sync_status, last_sync_message, validation_rules, created_at, updated_at, created_by_id, updated_by_id, phase_id, schema_summary) VALUES
(16, 'DS - 14M D.1 Data Source Evidence', '', 'POSTGRESQL', TRUE, '{"host": "localhost", "port": 5432, "database": "synapse_dt", "username": "synapse_user", "password": "synapse_password"}', 'basic', '{"username": "synapse_user", "password": "synapse_password"}', NULL, NULL, NULL, NULL, NULL, '2025-07-29T20:46:20.425868', '2025-07-29T20:46:20.425868', 6, 6, NULL, NULL);

