-- Seed data for workflow_activity_templates
-- Generated from: workflow_activity_templates.json
-- Rows: 50

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(137, 'Observation Management', 'Finalize Observations', 'APPROVAL', 5, 'Finalize observation status', TRUE, FALSE, 'Tester', NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'ManualActivityHandler', 172800, NULL, NULL, 'parallel', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(123, 'Request for Information', 'Send Data Request', 'TASK', 2, 'Send data upload request to data owner', FALSE, FALSE, NULL, NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'SendDataRequestHandler', 300, '{"max_attempts": 3, "initial_interval": 2, "max_interval": 60, "backoff": 2}', NULL, 'parallel', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(145, 'Data Profiling', 'Report Owner Rule Approval', 'APPROVAL', 4, 'Report Owner reviews and approves/rejects data profiling rules submitted by Tester. Each rule can be individually approved or rejected with feedback.', FALSE, FALSE, 'Report Owner', NULL, TRUE, '2025-07-16T02:56:36.678116+00:00', '2025-07-16T02:56:36.678116+00:00', 'ReportOwnerRuleApprovalHandler', 86400, '{"max_retries": 3, "retry_delay": 300}', NULL, 'sequential', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(141, 'Finalize Test Report', 'Review Report Draft', 'REVIEW', 3, 'Review and edit report draft', TRUE, FALSE, 'Tester', NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'ManualActivityHandler', 86400, NULL, NULL, 'sequential', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(124, 'Request for Information', 'Upload Data', 'TASK', 3, 'Data owner uploads requested data', TRUE, FALSE, 'Data Owner', NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'ManualActivityHandler', 86400, NULL, NULL, 'parallel', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(130, 'Test Execution', 'Review Test Results', 'REVIEW', 3, 'Review automated test results', TRUE, TRUE, 'Tester', NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'ManualActivityHandler', 86400, NULL, NULL, 'parallel', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(131, 'Test Execution', 'Document Test Evidence', 'TASK', 4, 'Document test execution evidence', TRUE, FALSE, 'Tester', NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'ManualActivityHandler', 86400, NULL, NULL, 'parallel', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(98, 'Planning', 'Review Generated Attributes', 'REVIEW', 3, 'Tester reviews and modifies generated attributes', TRUE, FALSE, 'Tester', NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'ManualActivityHandler', 86400, NULL, NULL, 'sequential', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(109, 'Scoping', 'Review Scoping Results', 'REVIEW', 3, 'Review and adjust scoping decisions', TRUE, FALSE, 'Tester', NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'ManualActivityHandler', 86400, NULL, NULL, 'sequential', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(110, 'Scoping', 'Scoping Approval', 'APPROVAL', 4, 'Approve final scope', TRUE, FALSE, 'Report Owner', NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'ManualActivityHandler', 172800, NULL, NULL, 'sequential', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(114, 'Sample Selection', 'Review and Tag Samples', 'TASK', 3, 'Review samples and ensure LOB tags are correct', TRUE, FALSE, 'Tester', NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'ManualActivityHandler', 86400, NULL, NULL, 'sequential', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(115, 'Sample Selection', 'Upload Additional Samples', 'TASK', 4, 'Upload any additional manual samples', TRUE, TRUE, 'Tester', NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'ManualActivityHandler', 86400, NULL, NULL, 'sequential', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(118, 'Data Owner Identification', 'Assign LOB Executives', 'TASK', 2, 'CDO assigns LOB executives based on sample tags', TRUE, FALSE, 'CDO', NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'ManualActivityHandler', 86400, NULL, NULL, 'sequential', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(119, 'Data Owner Identification', 'Assign Data Owners', 'TASK', 3, 'LOB executives assign data owners', TRUE, FALSE, 'Report Owner Executive', NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'ManualActivityHandler', 86400, NULL, NULL, 'sequential', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(120, 'Data Owner Identification', 'Assign Data Providers', 'TASK', 4, 'Data owners assign data providers', TRUE, FALSE, 'Data Owner', NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'ManualActivityHandler', 86400, NULL, NULL, 'sequential', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(99, 'Planning', 'Submit for Approval', 'REVIEW', 4, 'Submit attributes for report owner approval', TRUE, FALSE, 'Tester', NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'ManualActivityHandler', 86400, NULL, NULL, 'sequential', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(100, 'Planning', 'Report Owner Approval', 'APPROVAL', 5, 'Report owner approves test attributes', TRUE, FALSE, 'Report Owner', NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'ManualActivityHandler', 172800, NULL, NULL, 'sequential', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(142, 'Finalize Test Report', 'Quality Review', 'APPROVAL', 4, 'Quality review of test report', TRUE, FALSE, 'Test Manager', NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'ManualActivityHandler', 172800, NULL, NULL, 'sequential', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(96, 'Planning', 'Start Planning Phase', 'START', 1, 'Initialize planning phase', FALSE, FALSE, NULL, NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'AutomatedActivityHandler', 60, '{"max_attempts": 3, "initial_interval": 2, "max_interval": 60, "backoff": 2}', NULL, 'sequential', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(97, 'Planning', 'Generate Attributes', 'TASK', 2, 'Generate test attributes using LLM', FALSE, FALSE, 'Tester', NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'GenerateAttributesHandler', 900, '{"max_attempts": 3, "initial_interval": 2, "max_interval": 60, "backoff": 2}', NULL, 'sequential', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(107, 'Scoping', 'Start Scoping Phase', 'START', 1, 'Initialize scoping phase', FALSE, FALSE, NULL, NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'AutomatedActivityHandler', 60, '{"max_attempts": 3, "initial_interval": 2, "max_interval": 60, "backoff": 2}', NULL, 'sequential', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(108, 'Scoping', 'Execute Scoping', 'TASK', 2, 'Determine which attributes to test', FALSE, FALSE, 'Tester', NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'ExecuteScopingHandler', 1800, '{"max_attempts": 3, "initial_interval": 2, "max_interval": 60, "backoff": 2}', NULL, 'sequential', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(111, 'Scoping', 'Complete Scoping Phase', 'COMPLETE', 5, 'Finalize scoping phase', FALSE, FALSE, NULL, NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'AutomatedActivityHandler', 60, '{"max_attempts": 3, "initial_interval": 2, "max_interval": 60, "backoff": 2}', NULL, 'sequential', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(112, 'Sample Selection', 'Start Sample Selection', 'START', 1, 'Initialize sample selection phase', FALSE, FALSE, NULL, NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'AutomatedActivityHandler', 60, '{"max_attempts": 3, "initial_interval": 2, "max_interval": 60, "backoff": 2}', NULL, 'sequential', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(113, 'Sample Selection', 'Generate Samples', 'TASK', 2, 'Generate test samples with LOB tagging', FALSE, FALSE, 'Tester', NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'GenerateSamplesHandler', 900, '{"max_attempts": 3, "initial_interval": 2, "max_interval": 60, "backoff": 2}', NULL, 'sequential', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(116, 'Sample Selection', 'Complete Sample Selection', 'COMPLETE', 5, 'Finalize sample selection phase', FALSE, FALSE, NULL, NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'AutomatedActivityHandler', 60, '{"max_attempts": 3, "initial_interval": 2, "max_interval": 60, "backoff": 2}', NULL, 'sequential', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(117, 'Data Owner Identification', 'Start Data Owner ID', 'START', 1, 'Initialize data owner identification phase', FALSE, FALSE, NULL, NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'AutomatedActivityHandler', 60, '{"max_attempts": 3, "initial_interval": 2, "max_interval": 60, "backoff": 2}', NULL, 'sequential', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(121, 'Data Owner Identification', 'Complete Provider ID', 'COMPLETE', 5, 'Finalize data owner identification phase', FALSE, FALSE, NULL, NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'AutomatedActivityHandler', 60, '{"max_attempts": 3, "initial_interval": 2, "max_interval": 60, "backoff": 2}', NULL, 'sequential', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(122, 'Request for Information', 'Start Request Info', 'START', 1, 'Initialize request for information phase', FALSE, FALSE, NULL, NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'AutomatedActivityHandler', 60, '{"max_attempts": 3, "initial_interval": 2, "max_interval": 60, "backoff": 2}', NULL, 'sequential', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(135, 'Observation Management', 'Review Observations', 'REVIEW', 3, 'Review and categorize observations', TRUE, FALSE, 'Tester', NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'ManualActivityHandler', 86400, NULL, NULL, 'parallel', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(136, 'Observation Management', 'Data Owner Response', 'TASK', 4, 'Data owner provides response to observations', TRUE, FALSE, 'Data Owner', NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'ManualActivityHandler', 86400, NULL, NULL, 'parallel', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(106, 'Data Profiling', 'Complete Data Profiling', 'COMPLETE', 5, 'Finalize data profiling phase', FALSE, FALSE, NULL, NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'AutomatedActivityHandler', 60, '{"max_attempts": 3, "initial_interval": 2, "max_interval": 60, "backoff": 2}', NULL, 'sequential', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(105, 'Data Profiling', 'Review Profiling Results', 'REVIEW', 4, 'Review and validate profiling results', TRUE, FALSE, 'Tester', 'tester_rules_sent_for_approval', TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'ManualActivityHandler', 86400, NULL, NULL, 'sequential', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(103, 'Data Profiling', 'Upload Data Files', 'TASK', 2, 'Upload data files for profiling', TRUE, FALSE, 'Tester', NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'ManualActivityHandler', 86400, NULL, NULL, 'sequential', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(128, 'Test Execution', 'Start Test Execution', 'START', 1, 'Initialize test execution phase', FALSE, FALSE, NULL, NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'AutomatedActivityHandler', 60, '{"max_attempts": 3, "initial_interval": 2, "max_interval": 60, "backoff": 2}', NULL, 'sequential', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(133, 'Observation Management', 'Start Observation Management', 'START', 1, 'Initialize observation management phase', FALSE, FALSE, NULL, NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'AutomatedActivityHandler', 60, '{"max_attempts": 3, "initial_interval": 2, "max_interval": 60, "backoff": 2}', NULL, 'sequential', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(101, 'Planning', 'Complete Planning Phase', 'COMPLETE', 6, 'Finalize planning phase', FALSE, FALSE, NULL, NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'AutomatedActivityHandler', 60, '{"max_attempts": 3, "initial_interval": 2, "max_interval": 60, "backoff": 2}', NULL, 'sequential', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(140, 'Finalize Test Report', 'Generate Report Sections', 'TASK', 2, 'Generate test report sections', FALSE, FALSE, NULL, NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'GenerateReportSectionsHandler', 900, '{"max_attempts": 3, "initial_interval": 2, "max_interval": 60, "backoff": 2}', NULL, 'sequential', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(143, 'Finalize Test Report', 'Generate Final Report', 'TASK', 5, 'Generate final PDF report', FALSE, FALSE, NULL, NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'GenerateFinalReportHandler', 900, '{"max_attempts": 3, "initial_interval": 2, "max_interval": 60, "backoff": 2}', NULL, 'sequential', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(144, 'Finalize Test Report', 'Complete Report Finalization', 'COMPLETE', 6, 'Mark report as finalized', FALSE, FALSE, NULL, NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'AutomatedActivityHandler', 60, '{"max_attempts": 3, "initial_interval": 2, "max_interval": 60, "backoff": 2}', NULL, 'sequential', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(139, 'Finalize Test Report', 'Start Report Finalization', 'START', 1, 'Initialize report finalization phase', FALSE, FALSE, NULL, NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'AutomatedActivityHandler', 60, '{"max_attempts": 3, "initial_interval": 2, "max_interval": 60, "backoff": 2}', '{"all_observations_complete": true}', 'sequential', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(125, 'Request for Information', 'Validate Data Upload', 'TASK', 4, 'Validate uploaded data completeness', FALSE, FALSE, NULL, NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'ValidateDataUploadHandler', 300, '{"max_attempts": 3, "initial_interval": 2, "max_interval": 60, "backoff": 2}', NULL, 'parallel', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(126, 'Request for Information', 'Generate Test Cases', 'TASK', 5, 'Generate test cases for uploaded data', FALSE, FALSE, NULL, NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'GenerateTestCasesHandler', 900, '{"max_attempts": 3, "initial_interval": 2, "max_interval": 60, "backoff": 2}', NULL, 'parallel', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(127, 'Request for Information', 'Data Upload Complete', 'COMPLETE', 6, 'Mark data upload as complete', FALSE, FALSE, NULL, NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'AutomatedActivityHandler', 60, '{"max_attempts": 3, "initial_interval": 2, "max_interval": 60, "backoff": 2}', NULL, 'parallel', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(129, 'Test Execution', 'Execute Tests', 'TASK', 2, 'Execute tests on uploaded document', FALSE, FALSE, NULL, NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'ExecuteTestsHandler', 1800, '{"max_attempts": 3, "initial_interval": 2, "max_interval": 60, "backoff": 2}', NULL, 'parallel', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(132, 'Test Execution', 'Complete Test Execution', 'COMPLETE', 5, 'Mark test execution as complete', FALSE, FALSE, NULL, NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'AutomatedActivityHandler', 60, '{"max_attempts": 3, "initial_interval": 2, "max_interval": 60, "backoff": 2}', NULL, 'parallel', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(134, 'Observation Management', 'Create Observations', 'TASK', 2, 'Create observations for test failures', FALSE, FALSE, NULL, NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'CreateObservationsHandler', 300, '{"max_attempts": 3, "initial_interval": 2, "max_interval": 60, "backoff": 2}', NULL, 'parallel', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(138, 'Observation Management', 'Complete Observation Management', 'COMPLETE', 6, 'Mark observation management as complete', FALSE, FALSE, NULL, NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'AutomatedActivityHandler', 60, '{"max_attempts": 3, "initial_interval": 2, "max_interval": 60, "backoff": 2}', NULL, 'parallel', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(102, 'Data Profiling', 'Start Data Profiling', 'START', 1, 'Initialize data profiling phase', FALSE, FALSE, NULL, NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'AutomatedActivityHandler', 60, '{"max_attempts": 3, "initial_interval": 2, "max_interval": 60, "backoff": 2}', NULL, 'sequential', NULL, NULL);

INSERT INTO workflow_activity_templates (template_id, phase_name, activity_name, activity_type, activity_order, description, is_manual, is_optional, required_role, auto_complete_on_event, is_active, created_at, updated_at, handler_name, timeout_seconds, retry_policy, conditional_expression, execution_mode, created_by_id, updated_by_id) VALUES
(104, 'Data Profiling', 'Generate Data Profiling Rules', 'TASK', 3, 'Generate data profiling rules using AI', FALSE, FALSE, 'Tester', NULL, TRUE, '2025-07-11T12:49:49.623656+00:00', '2025-07-11T12:49:49.623656+00:00', 'DataProfilingHandler', 1800, '{"max_attempts": 3, "initial_interval": 2, "max_interval": 60, "backoff": 2}', NULL, 'sequential', NULL, NULL);

