-- Seed data for cycle_report_observation_mgmt_observation_records
-- Generated from: cycle_report_observation_mgmt_observation_records.json
-- Rows: 2

INSERT INTO cycle_report_observation_mgmt_observation_records (observation_id, phase_id, observation_title, observation_description, observation_type, severity, status, source_test_execution_id, source_sample_record_id, source_attribute_id, detection_method, detection_confidence, impact_description, impact_categories, financial_impact_estimate, regulatory_risk_level, affected_processes, affected_systems, evidence_documents, supporting_data, screenshots, related_observations, detected_by, assigned_to, detected_at, assigned_at, auto_detection_rules, auto_detection_score, manual_validation_required, created_at, updated_at, created_by_id, updated_by_id, tester_decision, tester_comments, tester_decision_by_id, tester_decision_at, report_owner_decision, report_owner_comments, report_owner_decision_by_id, report_owner_decision_at, approval_status) VALUES
(41, 481, 'Missing Documentation - Current Credit limit', 'No documentation found to validate the expected value for Current Credit limit', 'DOCUMENTATION', 'MEDIUM', 'DETECTED', 44, NULL, 400, 'Manual', NULL, NULL, 'null', NULL, NULL, 'null', 'null', 'null', '{"linked_test_executions": ["40"], "grouped_count": 2}', 'null', 'null', 3, NULL, '2025-08-01T21:35:56.742725', NULL, NULL, NULL, FALSE, '2025-08-01T21:35:56.715128+00:00', '2025-08-02T02:12:22.734170+00:00', 3, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Pending Review');

INSERT INTO cycle_report_observation_mgmt_observation_records (observation_id, phase_id, observation_title, observation_description, observation_type, severity, status, source_test_execution_id, source_sample_record_id, source_attribute_id, detection_method, detection_confidence, impact_description, impact_categories, financial_impact_estimate, regulatory_risk_level, affected_processes, affected_systems, evidence_documents, supporting_data, screenshots, related_observations, detected_by, assigned_to, detected_at, assigned_at, auto_detection_rules, auto_detection_score, manual_validation_required, created_at, updated_at, created_by_id, updated_by_id, tester_decision, tester_comments, tester_decision_by_id, tester_decision_at, report_owner_decision, report_owner_comments, report_owner_decision_by_id, report_owner_decision_at, approval_status) VALUES
(40, 481, 'Data Quality Issue - Current Credit limit', 'This is a DQ Issue', 'DATA_QUALITY', 'MEDIUM', 'DETECTED', 22, 'aee113b3-cdf7-4d2f-a29f-27a49aafd35f', 400, 'Manual', NULL, NULL, 'null', NULL, NULL, 'null', 'null', 'null', '{"linked_test_executions": ["43"], "grouped_count": 2}', 'null', 'null', 3, NULL, '2025-08-01T21:29:50.415716', NULL, NULL, NULL, FALSE, '2025-08-01T21:29:50.349964+00:00', '2025-08-02T02:23:59.388521+00:00', 3, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Pending Review');

