CREATE TABLE cycle_report_data_profiling_attribute_scores (
    score_id integer NOT NULL DEFAULT nextval('attribute_profiling_scores_score_id_seq'::regclass),
    phase_id integer NOT NULL,
    attribute_id integer NOT NULL,
    overall_quality_score double precision(53),
    completeness_score double precision(53),
    validity_score double precision(53),
    accuracy_score double precision(53),
    consistency_score double precision(53),
    uniqueness_score double precision(53),
    total_rules_executed integer,
    rules_passed integer,
    rules_failed integer,
    total_values integer,
    null_count integer,
    unique_count integer,
    data_type_detected character varying(50),
    pattern_detected character varying(255),
    distribution_type character varying(50),
    has_anomalies boolean,
    anomaly_count integer,
    anomaly_types json,
    testing_recommendation text,
    risk_assessment text,
    calculated_at timestamp without time zone NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY (score_id)
);
