"""add data dictionary fields to report attributes

Revision ID: 2a690861a41b
Revises: 8a35f71596ce
Create Date: 2025-06-07 15:45:46.340609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a690861a41b'
down_revision: Union[str, None] = '8a35f71596ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the new data dictionary fields to report_attributes table
    op.add_column('report_attributes', sa.Column('line_item_number', sa.String(length=20), nullable=True, comment='Regulatory line item number from data dictionary'))
    op.add_column('report_attributes', sa.Column('technical_line_item_name', sa.String(length=255), nullable=True, comment='Technical line item name from data dictionary'))
    op.add_column('report_attributes', sa.Column('mdrm', sa.String(length=50), nullable=True, comment='MDRM code from regulatory data dictionary'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove the data dictionary fields from report_attributes table
    op.drop_column('report_attributes', 'mdrm')
    op.drop_column('report_attributes', 'technical_line_item_name')
    op.drop_column('report_attributes', 'line_item_number')
    # ### end Alembic commands ###
