#!/usr/bin/env python3
"""Check sample decisions in detail"""

import asyncio
import httpx
import json

async def check_samples():
    async with httpx.AsyncClient() as client:
        # Login as Jane
        login = await client.post('http://localhost:8001/api/v1/auth/login', 
            json={'email': 'tester@example.com', 'password': 'password123'})
        
        if login.status_code != 200:
            print(f"Login failed: {login.status_code}")
            return
            
        token = login.json()['access_token']
        
        # Get samples
        resp = await client.get(
            'http://localhost:8001/api/v1/sample-selection/cycles/13/reports/156/samples',
            headers={'Authorization': f'Bearer {token}'}
        )
        
        if resp.status_code == 200:
            data = resp.json()
            print(f'\nTotal samples: {len(data["cycle_report_sample_selection_samples"])}\n')
            
            # Show samples S007 and S009 specifically
            for sample in data['samples']:
                if sample['sample_id'] in ['C13_R156_S007', 'C13_R156_S009']:
                    print(f'Sample {sample["sample_id"]}:')
                    print(f'  Generated By: {sample.get("generated_by", "Unknown")}')
                    print(f'  Tester Decision: {sample.get("tester_decision", "None")}')
                    print(f'  Report Owner Decision: {sample.get("report_owner_decision", "None")}')
                    print(f'  Is Submitted: {sample.get("is_submitted", False)}')
                    print(f'  Full data: {json.dumps(sample, indent=2)}')
                    print()

if __name__ == "__main__":
    asyncio.run(check_samples())